export interface IRowData {
  acquiring_bank: string;
  acquiring_fee: number;
  additional_payment: number;
  barcode: string
  brand_name: string
  commission_percent: number
  create_dt: string
  date_from: string
  date_to: string
  declaration_number: string
  delivery_amount: number
  delivery_rub: number
  doc_type_name: string
  gi_box_type_name: string
  gi_id: number
  nm_id: number
  office_name: string
  order_dt: string
  penalty: number
  ppvz_for_pay: number
  ppvz_inn: string
  ppvz_kvw_prc: number
  ppvz_kvw_prc_base: number
  ppvz_office_id: number
  ppvz_reward: number
  ppvz_sales_commission: number
  ppvz_spp_prc: number
  ppvz_supplier_id: number
  ppvz_supplier_name: string
  ppvz_vw: number
  ppvz_vw_nds: number
  product_discount_for_report: number
  quantity: number
  realizationreport_id: number
  retail_amount: number
  retail_price: number
  retail_price_withdisc_rub: number
  return_amount: number
  rid: number
  rr_dt: string
  rrd_id: number
  sa_name: string
  sale_dt: string
  sale_percent: number
  shk_id: number
  site_country: string
  srid: string
  sticker_id: string
  subject_name: string
  supplier_oper_name: string
  supplier_promo: number
  suppliercontract_code: null
  ts_name: string
}